import Foundation
@testable import FTWKit

/// The shared interop vectors, generated by srcfl/ftw from the web app's own
/// code (go/internal/appwire/testdata/generate-vectors.ts). The Go box replays
/// the same file; replaying it here puts three implementations on one wire.
struct InteropVectors: Decodable {
    struct Handshake: Decodable {
        let prologue: String
        let initiatorStatic: String
        let initiatorStaticPublic: String
        let initiatorEphemeral: String
        let responderStatic: String
        let responderStaticPublic: String
        let responderEphemeral: String
        let message1Payload: String
        let message1: String
        let message2Payload: String
        let message2: String
        let handshakeHash: String
    }

    struct FrameVector: Decodable {
        let name: String
        let lane: UInt8
        let flags: UInt8
        let bucket: Int
        let payloadLen: Int
        let envelopeKeys: [String]
        let bytes: String
    }

    struct TransportStep: Decodable {
        let from: String
        let frame: String
        let seq: UInt64
        let wire: String
    }

    let protocolName: String
    let handshake: Handshake
    let frames: [FrameVector]
    let transport: [TransportStep]

    static func load() throws -> InteropVectors {
        guard let url = Bundle.module.url(forResource: "webapp-vectors", withExtension: "json", subdirectory: "Resources") else {
            throw CocoaError(.fileNoSuchFile)
        }
        return try JSONDecoder().decode(InteropVectors.self, from: Data(contentsOf: url))
    }
}

/// Where the repository's shared files live, found from this file's path so
/// the tests read the real registry rather than a copy of it.
enum RepoFiles {
    static var root: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // FTWKitTests
            .deletingLastPathComponent() // Tests
            .deletingLastPathComponent() // appleApp
            .deletingLastPathComponent() // repository
    }

    static func read(_ path: String) throws -> String {
        try String(contentsOf: root.appendingPathComponent(path), encoding: .utf8)
    }
}

